import Link from "next/link";
import { LayoutTemplateIcon } from "lucide-react";
import { DocsPagination } from "@/components/docs/DocsPagination";
import { DocsHero } from "@/components/docs/DocsHero";
import { CodeBlock } from "@/components/docs/CodeBlock";
import { Callout } from "@/components/docs/Callout";
import {
	DocsSection,
	DocsSubheading,
	DocsList,
	Markup,
} from "@/components/docs/prose";

const folderStructure = `my-template/
├── anesis.template.json   ← required manifest
├── README.md.tera        ← rendered at generation time
├── package.json.tera     ← rendered at generation time
├── src/
│   ├── main.ts.tera
│   └── index.html
└── .gitignore            ← copied as-is (no .tera suffix)`;

const manifestExample = `{
  "name": "react-vite-ts",
  "version": "0.7.4",
  "anesisVersion": ">=0.7.0",
  "repository": {
    "url": "https://github.com/owner/repo/tree/main/templates/react-vite-ts"
  },
  "metadata": {
    "displayName": "React Vite TypeScript",
    "description": "Starter for React + Vite + TypeScript."
  }
}`;

const manifestFields = [
	{
		field: "name",
		description:
			"The template's identifier used in CLI commands. Must use only letters, numbers, hyphens, and underscores.",
	},
	{
		field: "version",
		description: "A semantic version string for the template itself.",
	},
	{
		field: "anesisVersion",
		description:
			'A semver range describing the minimum Anesis CLI version required. Use ">=0.7.0" to require at least that version.',
	},
	{
		field: "repository.url",
		description:
			"The GitHub URL where this template lives. Can be a repo root or a subdirectory path — this is the same URL passed to `anesis template publish`.",
	},
	{
		field: "metadata.displayName",
		description: "The human-readable name shown in the template registry UI.",
	},
	{
		field: "metadata.description",
		description: "A short sentence describing what this template creates.",
	},
];

const teraVariables = `# Available in every .tera file:
{{ project_name }}         # exactly what the user typed: "my-app"
{{ project_name_kebab }}   # lowercase with dashes: "my-app"
{{ project_name_snake }}   # lowercase with underscores: "my_app"`;

const teraFileExamples = `// package.json.tera
{
  "name": "{{ project_name_kebab }}",
  "version": "0.1.0"
}

// src/main.ts.tera
// {{ project_name }} — generated by Anesis
export const appName = "{{ project_name_snake }}";

// README.md.tera
# {{ project_name }}

This project was generated from the react-vite-ts template.`;

const pathRules = [
	"Files ending in `.tera` are rendered through the Tera template engine. The `.tera` suffix is stripped from the output filename — `package.json.tera` becomes `package.json`.",
	"Files without a `.tera` suffix are copied exactly as-is, with no rendering.",
	"Path traversal is blocked at extraction time. A template cannot write files outside the target project directory, regardless of how paths are constructed.",
];

export default function DocsTemplatesCreatingPage() {
	return (
		<div className="mx-auto flex w-full max-w-3xl flex-col gap-10 px-5 py-10 lg:px-8">
			<DocsHero
				eyebrow="Templates / Creating Templates"
				eyebrowIcon={LayoutTemplateIcon}
				title="Build your own template"
				description={
					<>
						A template is a folder of project files plus one required manifest:{" "}
						<code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">
							anesis.template.json
						</code>
						. Files ending in{" "}
						<code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">
							.tera
						</code>{" "}
						are rendered with the user&apos;s project name substituted in at
						generation time. Everything else is copied exactly as-is.
					</>
				}
				chips={[
					"anesis.template.json manifest",
					"Tera template rendering",
					"project_name variables",
				]}
			/>

			<div className="flex flex-col gap-10">
				<DocsSection
					id="folder"
					title="Folder structure"
					lead="Your template is a regular directory. The only required file is the manifest at the root — everything else is up to you."
				>
					<CodeBlock code={folderStructure} />
				</DocsSection>

				<DocsSection
					id="file-types"
					title="The two kinds of files"
					lead="Anesis decides at generation time whether to render or copy each file."
				>
					<DocsSubheading id="tera-files">*.tera files</DocsSubheading>
					<p>
						Rendered through the Tera template engine. The <code>.tera</code>{" "}
						suffix is removed from the output filename. Use these for any file
						that should contain the project name.
					</p>

					<DocsSubheading id="other-files">All other files</DocsSubheading>
					<p>
						Copied exactly as-is — the content is not modified. Use these for
						binary files, lockfiles, or any file that should never change between
						projects.
					</p>
				</DocsSection>

				<DocsSection
					id="manifest"
					title="The anesis.template.json manifest"
					lead="This file must be at the root of your template directory. The CLI reads it to populate the cache index and display metadata in the registry."
				>
					<CodeBlock code={manifestExample} />
					<dl className="space-y-3">
						{manifestFields.map((item) => (
							<div
								key={item.field}
								className="flex flex-col gap-1 sm:flex-row sm:gap-4"
							>
								<dt className="sm:w-48 sm:shrink-0">
									<code className="rounded bg-muted px-2 py-0.5 font-mono text-xs text-foreground">
										{item.field}
									</code>
								</dt>
								<dd className="text-muted-foreground">
									<Markup>{item.description}</Markup>
								</dd>
							</div>
						))}
					</dl>
				</DocsSection>

				<DocsSection
					id="variables"
					title="Available template variables"
					lead="Three forms of the project name are injected into the Tera context automatically. There are no other built-in variables."
				>
					<CodeBlock code={teraVariables} />
					<p>
						<code>project_name_kebab</code> and <code>project_name_snake</code>{" "}
						are derived automatically — you don&apos;t need to do any string
						manipulation in your templates.
					</p>

					<DocsSubheading id="variable-usage">
						Variable usage in .tera files
					</DocsSubheading>
					<p>
						Use the Tera double-brace syntax anywhere in a <code>.tera</code>{" "}
						file. The output filename has the <code>.tera</code> suffix removed.
					</p>
					<CodeBlock code={teraFileExamples} />
				</DocsSection>

				<DocsSection
					id="safety"
					title="File processing rules and safety"
					lead="These rules are enforced by the CLI during extraction and rendering."
				>
					<DocsList items={pathRules} />
				</DocsSection>

				<DocsSection
					id="testing"
					title="Testing your template locally"
					lead="You don't need to publish to test."
				>
					<Callout variant="tip" title="Local test loop">
						<p>
							Install from a local path with <code>anesis template install</code>{" "}
							pointing at your directory, then run{" "}
							<code>anesis new test-project my-template</code> to verify the
							output. Check that <code>.tera</code> files render correctly and
							that all plain files are copied intact.
						</p>
					</Callout>
					<p>
						When it looks right, continue to{" "}
						<Link
							href="/docs/templates/publishing"
							className="font-medium text-primary hover:underline"
						>
							Publishing your template →
						</Link>
					</p>
				</DocsSection>
			</div>

			<DocsPagination currentHref="/docs/templates/creating" />
		</div>
	);
}
